include:
  - management/docker-compose.yml
  - frontend/docker-compose.yml

services:
  docs:
    build: ./docs
    ports:
      - "8000:8000"
    volumes:
      - ./mkdocs.yml:/mkdocs.yml
    networks:
      - local-cfp-net

  rabbitmq:
    build: ./rabbitmq
    hostname: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - local-cfp-net

  redis:
    build: ./redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - local-cfp-net

  scraper:
    build: ./scraper
    env_file:
      - .env
    ports:
      - "5015:5005"
    networks:
      - local-cfp-net

  classifier:
    build:
      context: ./classifier
      dockerfile: Dockerfile
    command: ["python", "-m", "app.classifier"]
    env_file:
      - .env
    environment:
      - OPENROUTER_API_KEY=${CLASSIFIER_OPENROUTER_API_KEY}
    volumes:
      # Cache for a local model
      - huggingface_cache:/app/huggingface_cache
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - local-cfp-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev --import-realm
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/keycloak-realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - local-cfp-net

  chat-server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - local-cfp-net

volumes:
  rabbitmq_data:
  redis-data:
  postgres-data:
  huggingface_cache: { }

networks:
  local-cfp-net:
    name: local-cfp-net
    driver: bridge