# mkdocs.yml
site_name: 'ILO CfP Classifier Documentation'
theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

nav:
  - 'Home': 'index.md'
  - 'System Architecture': 'architecture.md'
  - 'Deployment': 'deployment.md'
  - 'Services':
      - 'RabbitMQ': 'services/rabbitmq.md'
      - 'Management': 'services/management.md'

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format