# Prevents the default "guest" user from connecting remotely
loopback_users.guest = false
definitions.import_backend = local_filesystem
definitions.skip_if_unchanged = true
definitions.local.path = /etc/rabbitmq/definitions.json