# This dictionary maps lowercase country names to their corresponding regions.
# Data is sourced from the ILO member and non-member states lists.

COUNTRY_REGION_MAP = {
    "afghanistan": "Asia",
    "albania": "Europe and Central Asia",
    "algeria": "Africa",
    "angola": "Africa",
    "antigua and barbuda": "Caribbean",
    "argentina": "Americas",
    "armenia": "Europe and Central Asia",
    "australia": "Pacific",
    "austria": "EU",
    "azerbaijan": "Europe and Central Asia",
    "bahamas": "Caribbean",
    "bahrain": "Arab States",
    "bangladesh": "Asia",
    "barbados": "Caribbean",
    "belarus": "Europe and Central Asia",
    "belgium": "EU",
    "belize": "Caribbean",
    "benin": "Africa",
    "bolivia (plurinational state of)": "Americas",
    "bosnia and herzegovina": "Europe and Central Asia",
    "botswana": "Africa",
    "brazil": "Americas",
    "brunei darussalam": "Asia",
    "bulgaria": "EU",
    "burkina faso": "Africa",
    "burundi": "Africa",
    "cabo verde": "Africa",
    "cambodia": "Asia",
    "cameroon": "Africa",
    "canada": "Americas",
    "central african republic": "Africa",
    "chad": "Africa",
    "chile": "Americas",
    "china": "Asia",
    "colombia": "Americas",
    "comoros": "Africa",
    "congo": "Africa",
    "cook islands": "Pacific",
    "costa rica": "Americas",
    "côte d'ivoire": "Africa",
    "croatia": "EU",
    "cuba": "Americas",
    "cyprus": "EU",
    "czechia": "EU",
    "democratic republic of the congo": "Africa",
    "denmark": "EU",
    "djibouti": "Africa",
    "dominica": "Caribbean",
    "dominican republic": "Americas",
    "ecuador": "Americas",
    "egypt": "Africa",
    "el salvador": "Americas",
    "equatorial guinea": "Africa",
    "eritrea": "Africa",
    "estonia": "EU",
    "eswatini": "Africa",
    "ethiopia": "Africa",
    "fiji": "Pacific",
    "finland": "EU",
    "france": "EU",
    "gabon": "Africa",
    "gambia": "Africa",
    "georgia": "Europe and Central Asia",
    "germany": "EU",
    "ghana": "Africa",
    "greece": "EU",
    "grenada": "Caribbean",
    "guatemala": "Americas",
    "guinea": "Africa",
    "guinea-bissau": "Africa",
    "guyana": "Caribbean",
    "haiti": "Americas",
    "honduras": "Americas",
    "hungary": "EU",
    "iceland": "Europe and Central Asia",
    "india": "Asia",
    "indonesia": "Asia",
    "iran (islamic republic of)": "Asia",
    "iraq": "Arab States",
    "ireland": "EU",
    "israel": "Europe and Central Asia",
    "italy": "EU",
    "jamaica": "Caribbean",
    "japan": "Asia",
    "jordan": "Arab States",
    "kazakhstan": "Europe and Central Asia",
    "kenya": "Africa",
    "kiribati": "Pacific",
    "kuwait": "Arab States",
    "kyrgyzstan": "Europe and Central Asia",
    "lao people's democratic republic": "Asia",
    "latvia": "EU",
    "lebanon": "Arab States",
    "lesotho": "Africa",
    "liberia": "Africa",
    "libya": "Africa",
    "lithuania": "EU",
    "luxembourg": "EU",
    "madagascar": "Africa",
    "malawi": "Africa",
    "malaysia": "Asia",
    "maldives": "Asia",
    "mali": "Africa",
    "malta": "EU",
    "marshall islands": "Pacific",
    "mauritania": "Africa",
    "mauritius": "Africa",
    "mexico": "Americas",
    "mongolia": "Asia",
    "montenegro": "Europe and Central Asia",
    "morocco": "Africa",
    "mozambique": "Africa",
    "myanmar": "Asia",
    "namibia": "Africa",
    "nepal": "Asia",
    "netherlands": "EU",
    "new zealand": "Pacific",
    "nicaragua": "Americas",
    "niger": "Africa",
    "nigeria": "Africa",
    "north macedonia": "Europe and Central Asia",
    "norway": "Europe and Central Asia",
    "oman": "Arab States",
    "pakistan": "Asia",
    "palau": "Pacific",
    "panama": "Americas",
    "papua new guinea": "Pacific",
    "paraguay": "Americas",
    "peru": "Americas",
    "philippines": "Asia",
    "poland": "EU",
    "portugal": "EU",
    "qatar": "Arab States",
    "republic of korea": "Asia",
    "republic of moldova": "Europe and Central Asia",
    "romania": "EU",
    "russian federation": "Europe and Central Asia",
    "rwanda": "Africa",
    "saint kitts and nevis": "Caribbean",
    "saint lucia": "Caribbean",
    "saint vincent and the grenadines": "Caribbean",
    "samoa": "Pacific",
    "san marino": "Europe and Central Asia",
    "sao tome and principe": "Africa",
    "saudi arabia": "Arab States",
    "senegal": "Africa",
    "serbia": "Europe and Central Asia",
    "seychelles": "Africa",
    "sierra leone": "Africa",
    "singapore": "Asia",
    "slovakia": "EU",
    "slovenia": "EU",
    "solomon islands": "Pacific",
    "somalia": "Africa",
    "south africa": "Africa",
    "south sudan": "Africa",
    "spain": "EU",
    "sri lanka": "Asia",
    "sudan": "Africa",
    "suriname": "Caribbean",
    "sweden": "EU",
    "switzerland": "Europe and Central Asia",
    "syrian arab republic": "Arab States",
    "syria": "Arab States",
    "tajikistan": "Europe and Central Asia",
    "thailand": "Asia",
    "timor-leste": "Asia",
    "togo": "Africa",
    "tonga": "Pacific",
    "trinidad and tobago": "Caribbean",
    "tunisia": "Africa",
    "türkiye": "Europe and Central Asia",
    "turkmenistan": "Europe and Central Asia",
    "tuvalu": "Pacific",
    "uganda": "Africa",
    "ukraine": "Europe and Central Asia",
    "united arab emirates": "Arab States",
    "united kingdom": "Europe and Central Asia",
    "united republic of tanzania": "Africa",
    "united states": "Americas",
    "usa": "Americas",
    "united states of america": "Americas",
    "uruguay": "Americas",
    "uzbekistan": "Europe and Central Asia",
    "vanuatu": "Pacific",
    "venezuela (bolivarian republic of)": "Americas",
    "vietnam": "Asia",
    "viet nam": "Asia",
    "yemen": "Arab States",
    "zambia": "Africa",
    "zimbabwe": "Africa",
    "andorra": "Non-Member",
    "bhutan": "Non-Member",
    "liechtenstein": "Non-Member",
    "micronesia": "Non-Member",
    "monaco": "Non-Member",
    "nauru": "Non-Member",
    "north korea": "Non-Member",
}