/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as workspace_workspaceRouteImport } from './routes/(workspace)/__workspace'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as workspace_workspaceUnauthorizedRouteImport } from './routes/(workspace)/__workspace.unauthorized'
import { Route as workspace_workspaceSourcesRouteImport } from './routes/(workspace)/__workspace.sources'
import { Route as workspace_workspaceFeedbackSummariesRouteImport } from './routes/(workspace)/__workspace.feedback-summaries'
import { Route as workspace_workspaceCriterionTypesRouteImport } from './routes/(workspace)/__workspace.criterion-types'
import { Route as workspace_workspaceScrapperResultsIndexRouteImport } from './routes/(workspace)/__workspace.scrapper-results.index'
import { Route as workspace_workspaceProposalsIndexRouteImport } from './routes/(workspace)/__workspace.proposals.index'
import { Route as workspace_workspaceScrapperResultsIdRouteImport } from './routes/(workspace)/__workspace.scrapper-results.$id'
import { Route as workspace_workspaceProposalsIdIndexRouteImport } from './routes/(workspace)/__workspace.proposals.$id.index'
import { Route as workspace_workspaceProposalsIdFeedbackRouteImport } from './routes/(workspace)/__workspace.proposals.$id.feedback'

const workspaceRouteImport = createFileRoute('/(workspace)')()

const workspaceRoute = workspaceRouteImport.update({
  id: '/(workspace)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const workspace_workspaceRoute = workspace_workspaceRouteImport.update({
  id: '/__workspace',
  getParentRoute: () => workspaceRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const workspace_workspaceUnauthorizedRoute =
  workspace_workspaceUnauthorizedRouteImport.update({
    id: '/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => workspace_workspaceRoute,
  } as any)
const workspace_workspaceSourcesRoute =
  workspace_workspaceSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => workspace_workspaceRoute,
  } as any)
const workspace_workspaceFeedbackSummariesRoute =
  workspace_workspaceFeedbackSummariesRouteImport.update({
    id: '/feedback-summaries',
    path: '/feedback-summaries',
    getParentRoute: () => workspace_workspaceRoute,
  } as any)
const workspace_workspaceCriterionTypesRoute =
  workspace_workspaceCriterionTypesRouteImport.update({
    id: '/criterion-types',
    path: '/criterion-types',
    getParentRoute: () => workspace_workspaceRoute,
  } as any)
const workspace_workspaceScrapperResultsIndexRoute =
  workspace_workspaceScrapperResultsIndexRouteImport.update({
    id: '/scrapper-results/',
    path: '/scrapper-results/',
    getParentRoute: () => workspace_workspaceRoute,
  } as any)
const workspace_workspaceProposalsIndexRoute =
  workspace_workspaceProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => workspace_workspaceRoute,
  } as any)
const workspace_workspaceScrapperResultsIdRoute =
  workspace_workspaceScrapperResultsIdRouteImport.update({
    id: '/scrapper-results/$id',
    path: '/scrapper-results/$id',
    getParentRoute: () => workspace_workspaceRoute,
  } as any)
const workspace_workspaceProposalsIdIndexRoute =
  workspace_workspaceProposalsIdIndexRouteImport.update({
    id: '/proposals/$id/',
    path: '/proposals/$id/',
    getParentRoute: () => workspace_workspaceRoute,
  } as any)
const workspace_workspaceProposalsIdFeedbackRoute =
  workspace_workspaceProposalsIdFeedbackRouteImport.update({
    id: '/proposals/$id/feedback',
    path: '/proposals/$id/feedback',
    getParentRoute: () => workspace_workspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof workspace_workspaceRouteWithChildren
  '/login': typeof authLoginRoute
  '/criterion-types': typeof workspace_workspaceCriterionTypesRoute
  '/feedback-summaries': typeof workspace_workspaceFeedbackSummariesRoute
  '/sources': typeof workspace_workspaceSourcesRoute
  '/unauthorized': typeof workspace_workspaceUnauthorizedRoute
  '/scrapper-results/$id': typeof workspace_workspaceScrapperResultsIdRoute
  '/proposals': typeof workspace_workspaceProposalsIndexRoute
  '/scrapper-results': typeof workspace_workspaceScrapperResultsIndexRoute
  '/proposals/$id/feedback': typeof workspace_workspaceProposalsIdFeedbackRoute
  '/proposals/$id': typeof workspace_workspaceProposalsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof workspace_workspaceRouteWithChildren
  '/login': typeof authLoginRoute
  '/criterion-types': typeof workspace_workspaceCriterionTypesRoute
  '/feedback-summaries': typeof workspace_workspaceFeedbackSummariesRoute
  '/sources': typeof workspace_workspaceSourcesRoute
  '/unauthorized': typeof workspace_workspaceUnauthorizedRoute
  '/scrapper-results/$id': typeof workspace_workspaceScrapperResultsIdRoute
  '/proposals': typeof workspace_workspaceProposalsIndexRoute
  '/scrapper-results': typeof workspace_workspaceScrapperResultsIndexRoute
  '/proposals/$id/feedback': typeof workspace_workspaceProposalsIdFeedbackRoute
  '/proposals/$id': typeof workspace_workspaceProposalsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(workspace)': typeof workspaceRouteWithChildren
  '/(workspace)/__workspace': typeof workspace_workspaceRouteWithChildren
  '/(workspace)/__workspace/criterion-types': typeof workspace_workspaceCriterionTypesRoute
  '/(workspace)/__workspace/feedback-summaries': typeof workspace_workspaceFeedbackSummariesRoute
  '/(workspace)/__workspace/sources': typeof workspace_workspaceSourcesRoute
  '/(workspace)/__workspace/unauthorized': typeof workspace_workspaceUnauthorizedRoute
  '/(workspace)/__workspace/scrapper-results/$id': typeof workspace_workspaceScrapperResultsIdRoute
  '/(workspace)/__workspace/proposals/': typeof workspace_workspaceProposalsIndexRoute
  '/(workspace)/__workspace/scrapper-results/': typeof workspace_workspaceScrapperResultsIndexRoute
  '/(workspace)/__workspace/proposals/$id/feedback': typeof workspace_workspaceProposalsIdFeedbackRoute
  '/(workspace)/__workspace/proposals/$id/': typeof workspace_workspaceProposalsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/criterion-types'
    | '/feedback-summaries'
    | '/sources'
    | '/unauthorized'
    | '/scrapper-results/$id'
    | '/proposals'
    | '/scrapper-results'
    | '/proposals/$id/feedback'
    | '/proposals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/criterion-types'
    | '/feedback-summaries'
    | '/sources'
    | '/unauthorized'
    | '/scrapper-results/$id'
    | '/proposals'
    | '/scrapper-results'
    | '/proposals/$id/feedback'
    | '/proposals/$id'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(workspace)'
    | '/(workspace)/__workspace'
    | '/(workspace)/__workspace/criterion-types'
    | '/(workspace)/__workspace/feedback-summaries'
    | '/(workspace)/__workspace/sources'
    | '/(workspace)/__workspace/unauthorized'
    | '/(workspace)/__workspace/scrapper-results/$id'
    | '/(workspace)/__workspace/proposals/'
    | '/(workspace)/__workspace/scrapper-results/'
    | '/(workspace)/__workspace/proposals/$id/feedback'
    | '/(workspace)/__workspace/proposals/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  workspaceRoute: typeof workspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(workspace)': {
      id: '/(workspace)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof workspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(workspace)/__workspace': {
      id: '/(workspace)/__workspace'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof workspace_workspaceRouteImport
      parentRoute: typeof workspaceRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(workspace)/__workspace/unauthorized': {
      id: '/(workspace)/__workspace/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof workspace_workspaceUnauthorizedRouteImport
      parentRoute: typeof workspace_workspaceRoute
    }
    '/(workspace)/__workspace/sources': {
      id: '/(workspace)/__workspace/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof workspace_workspaceSourcesRouteImport
      parentRoute: typeof workspace_workspaceRoute
    }
    '/(workspace)/__workspace/feedback-summaries': {
      id: '/(workspace)/__workspace/feedback-summaries'
      path: '/feedback-summaries'
      fullPath: '/feedback-summaries'
      preLoaderRoute: typeof workspace_workspaceFeedbackSummariesRouteImport
      parentRoute: typeof workspace_workspaceRoute
    }
    '/(workspace)/__workspace/criterion-types': {
      id: '/(workspace)/__workspace/criterion-types'
      path: '/criterion-types'
      fullPath: '/criterion-types'
      preLoaderRoute: typeof workspace_workspaceCriterionTypesRouteImport
      parentRoute: typeof workspace_workspaceRoute
    }
    '/(workspace)/__workspace/scrapper-results/': {
      id: '/(workspace)/__workspace/scrapper-results/'
      path: '/scrapper-results'
      fullPath: '/scrapper-results'
      preLoaderRoute: typeof workspace_workspaceScrapperResultsIndexRouteImport
      parentRoute: typeof workspace_workspaceRoute
    }
    '/(workspace)/__workspace/proposals/': {
      id: '/(workspace)/__workspace/proposals/'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof workspace_workspaceProposalsIndexRouteImport
      parentRoute: typeof workspace_workspaceRoute
    }
    '/(workspace)/__workspace/scrapper-results/$id': {
      id: '/(workspace)/__workspace/scrapper-results/$id'
      path: '/scrapper-results/$id'
      fullPath: '/scrapper-results/$id'
      preLoaderRoute: typeof workspace_workspaceScrapperResultsIdRouteImport
      parentRoute: typeof workspace_workspaceRoute
    }
    '/(workspace)/__workspace/proposals/$id/': {
      id: '/(workspace)/__workspace/proposals/$id/'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof workspace_workspaceProposalsIdIndexRouteImport
      parentRoute: typeof workspace_workspaceRoute
    }
    '/(workspace)/__workspace/proposals/$id/feedback': {
      id: '/(workspace)/__workspace/proposals/$id/feedback'
      path: '/proposals/$id/feedback'
      fullPath: '/proposals/$id/feedback'
      preLoaderRoute: typeof workspace_workspaceProposalsIdFeedbackRouteImport
      parentRoute: typeof workspace_workspaceRoute
    }
  }
}

interface workspace_workspaceRouteChildren {
  workspace_workspaceCriterionTypesRoute: typeof workspace_workspaceCriterionTypesRoute
  workspace_workspaceFeedbackSummariesRoute: typeof workspace_workspaceFeedbackSummariesRoute
  workspace_workspaceSourcesRoute: typeof workspace_workspaceSourcesRoute
  workspace_workspaceUnauthorizedRoute: typeof workspace_workspaceUnauthorizedRoute
  workspace_workspaceScrapperResultsIdRoute: typeof workspace_workspaceScrapperResultsIdRoute
  workspace_workspaceProposalsIndexRoute: typeof workspace_workspaceProposalsIndexRoute
  workspace_workspaceScrapperResultsIndexRoute: typeof workspace_workspaceScrapperResultsIndexRoute
  workspace_workspaceProposalsIdFeedbackRoute: typeof workspace_workspaceProposalsIdFeedbackRoute
  workspace_workspaceProposalsIdIndexRoute: typeof workspace_workspaceProposalsIdIndexRoute
}

const workspace_workspaceRouteChildren: workspace_workspaceRouteChildren = {
  workspace_workspaceCriterionTypesRoute:
    workspace_workspaceCriterionTypesRoute,
  workspace_workspaceFeedbackSummariesRoute:
    workspace_workspaceFeedbackSummariesRoute,
  workspace_workspaceSourcesRoute: workspace_workspaceSourcesRoute,
  workspace_workspaceUnauthorizedRoute: workspace_workspaceUnauthorizedRoute,
  workspace_workspaceScrapperResultsIdRoute:
    workspace_workspaceScrapperResultsIdRoute,
  workspace_workspaceProposalsIndexRoute:
    workspace_workspaceProposalsIndexRoute,
  workspace_workspaceScrapperResultsIndexRoute:
    workspace_workspaceScrapperResultsIndexRoute,
  workspace_workspaceProposalsIdFeedbackRoute:
    workspace_workspaceProposalsIdFeedbackRoute,
  workspace_workspaceProposalsIdIndexRoute:
    workspace_workspaceProposalsIdIndexRoute,
}

const workspace_workspaceRouteWithChildren =
  workspace_workspaceRoute._addFileChildren(workspace_workspaceRouteChildren)

interface workspaceRouteChildren {
  workspace_workspaceRoute: typeof workspace_workspaceRouteWithChildren
}

const workspaceRouteChildren: workspaceRouteChildren = {
  workspace_workspaceRoute: workspace_workspaceRouteWithChildren,
}

const workspaceRouteWithChildren = workspaceRoute._addFileChildren(
  workspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  workspaceRoute: workspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
